export const Greetings = {
  default: [
    'Hello!',
    "Howdy y'all",
    "I'll give it my best shot!",
    'Ayo what up',
    'Go Bears!',
    "Let's wait for more players.",
    "I'm using tilt controls!",
    'Shall we get started?',
  ],
  Harvard: ['Roll Crimson Tide', 'Home of the OG Datamatch'],
  Dartmouth: ['phi delt beta apple pi omega chi'],
  BC: ['hoc est corpus meum'],
  BU: ['hello Terriers!'],
  Caltech: ['who else is also procrastinating on midterms?'],
  Brown: ['uwu hewwo!'],
  FIT: ['hey babes!'],
  'UW Madison': ["jumpin' around"],
  McGill: ['happy matching mcgillians <3'],
  Smith: [
    'what if we kissed by Kathy’s doorsteps 🤪?.. jk haha… unless? 🥺 👉👈',
  ],
  'UC Davis': ['welcome Aggies!'],
  UCLA: ["how's it going yall", 'add me on costar'],
  UChicago: ['hi!', "this is the most fun i've had in years"],
  UIUC: ['I-L-L', "don't mind me, just hanging out in the corn fields"],
  UCSD: ['good morning, gamers'],
  CMU: ['hey yinz'],
  Vanderbilt: ['welcome lonely Dores :)'],
  Princeton: ['Meet me at the chapel 😜'],
};
