// Used in utils/updateProfiles.js
export const profileFields = {
  smallProfile: ['college', 'name', 'onboarded', 'profile_pic'],
  publicProfile: [
    'college',
    'description',
    'dorm', // TODO: Move under location
    'facebook',
    'instagram',
    'location',
    'meet',
    'name',
    'privacy',
    'profile_pic',
    'prompt',
    'snapchat',
    'spotifyTopArtists',
    'spotifyUserLink',
    'tiktok',
    'times',
    'timezone',
    'year',
    'zoom',
  ],
  privateProfile: [
    'blocklist',
    'crossMatch',
    'email',
    'gender',
    'lookingFor',
    'lookingForGender',
    'matchCategory',
    'noDormMatch',
    'pronouns',
    'show',
    'signupNum',
    'similar',
    'spotifyRefreshToken',
  ],
};
