import { headerHeight } from 'constants/Navbar';

export const pageMessagesSx = {
  display: 'flex',
  height: 'calc(100vh - '.concat(headerHeight.toString()).concat('px)'),
  // 'calc(100vh - 70px)'

  '.messages-sidebar-mobile': {
    flex: '0 0 100%',
    backgroundColor: '#fff',
    maxWidth: '100vw',
    top: 0,
    bottom: 0,
    overflowY: 'scroll',
  },

  '.view-profilePic': {
    width: '30px',
    height: '30px',
    borderRadius: '50%',
    display: 'inline-block',
    marginRight: '8px',
  },

  '.messages-sidebar': {
    flex: '0 0 250px',
    backgroundColor: '#fff',
    maxWidth: '400px',
    top: 0,
    bottom: 0,
    overflowY: 'scroll',
  },

  '.messages-description': {
    margin: '20px 20px',
  },

  '.messages-match': {
    display: 'flex',
    padding: '20px 20px',
    cursor: 'pointer',
    borderTop: '#e7e7e7 1px solid',
    borderBottom: '#e7e7e7 1px solid',
    ':hover': {
      backgroundColor: '#fcfcfc',
    },
  },

  '.unread': {
    fontWeight: 700,
  },

  '.no-results': {
    paddingTop: '20px',
    marginTop: '20px',
    borderTop: '#e7e7e7 1px solid',
  },

  '.selected': {
    backgroundColor: '#fcfcfc',
  },

  '.profile-preview': {
    flex: '0 0 275px',
    padding: '20px',
    backgroundColor: '#fff',
    overflow: 'auto',
  },

  '.next-match': {
    marginBottom: '20px',
    color: '#524f6c',
    cursor: 'pointer',
    fontSize: '16px',
  },
};

export const chatSx = {
  backgroundColor: '#fcfcfc',
  boxShadow: '0 1px 4px rgba(0, 0, 0, 0.3)',
  width: '100%',
  position: 'relative',

  '.chatbox': {
    height: '70px',
    backgroundColor: '#fff',
    fontSize: '14px',
    padding: '20px 20px',
    boxShadow: 'rgba(0, 0, 0, 0.15) 0px -2px 4px',
  },

  '.textbox': {
    height: '30px',
    borderRadius: '3px',
    background: '#f4f2f2',
  },

  '.sendButton': {
    width: '60px',
    marginLeft: '30px',
    padding: '0px',
  },

  '.messagesContainer': {
    width: '100%',
    overflow: 'auto',
    border: '1px solid #dadde1',
  },

  '.message': {
    padding: '5px 10px',
    backgroundcolor: '#fcfcfc',
  },

  '.messageText': {
    display: 'inline-block',
    textAlign: 'left',
    padding: '5px 10px',
    border: '#b1b1b1 solid 1px',
    borderRadius: '3px',
    backgroundColor: '#fff',
    maxWidth: '75%',
    overflowWrap: 'break-word',
  },

  '.autogenerated': {
    backgroundColor: '#f09e9d',
  },

  '.messageTime': {
    display: 'block',
    opacity: '0.5',
    overflowWrap: 'break-word',
    fontSize: '10px',
  },

  '.messageBox': {
    display: ' inline-block',
    padding: '5px 10px',
    border: '#b1b1b1 solid 1px',
    borderRadius: '3px',
    backgroundColor: '#fff',
    maxWidth: '75%',
    overflowWrap: 'break-word',
    lineHeight: '20px',
  },

  '.dateDisplay': {
    margin: 'auto',
    textAlign: 'center',
    fontSize: '12px',
    opacity: '0.5',
    padding: '5px 10px',
  },
};

export const matchChatSx = {
  backgroundColor: '#fcfcfc',
  boxShadow: '0 1px 4px rgba(0, 0, 0, 0.3)',
  width: '100%',
  position: 'relative',
  textAlign: 'center',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  padding: '10px',

  '.description': {
    marginBottom: '10px',
    fontSize: '20px',
    fontWeight: '700',
  },
};
